services:
  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: recruitment-backend-dev
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb+srv://Bharathi123:Bharathi123@cluster0.q0k9nft.mongodb.net/ats_recruitment?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    networks:
      - recruitment-network-dev
    volumes:
      - ./backend:/app
      - /app/venv
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Application (Development with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: recruitment-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - recruitment-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

networks:
  recruitment-network-dev:
    driver: bridge

 