services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitment-backend
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    networks:
      - recruitment-network
    volumes:
      - ./backend:/app
      - /app/venv

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recruitment-frontend
    restart: unless-stopped
    env_file:
      - frontend/.env
    environment:
      - VITE_BACKEND_URL=http://13.232.219.238:8000
      - FRONTEND_PORT=80
      - BACKEND_URL=http://13.232.219.238:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge

 